### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by mark818**
This branch:

- Builds the filter bar on "index" and "show"

- Updates markers based on filter requirements using AJAX

- **Eliminates hard coded JSON and uses Google Map Geocoding API instead**

- Adds tests passing locally

- rebased master to be able to FF.

### CODE REVIEW

**Review by zhanshi-wang — APPROVED** [review]
Looks good to me 💯 .
All the filter features of the user stories for this iteration works as expected. We can keep the filter between the filters.
Yeah~

**Comment by kathrynwu** [comment]
Looks good to me 💯 
All the functions work good 👌
I see all the filter work good with all the work we did.

**Review by kathrynwu — APPROVED** [review]

**Review by aandreassa — APPROVED** [review]
Logic for filter and map look good to me

**Review by sunsun1001 — APPROVED** [review]
Looks good. We need to change the geolocator logic so that our markers are consistent. Will address in iteration 3. Also it may be useful to change the xhttp url to {name}%20Hall%20Berkeley. I found more halls with the updated dB this way. Good work 👍

**Comment by jain-nikunj** [comment]
Lgtm, continuous integration looks clean

**Pull request merged**
