### PR TITLE
Revamped Google Map Marker Tooltip

### PR DESCRIPTION
**Pull request by mark818**
- Revamped tooltip with room count and max capacity.

- Updated controller filter logic to include room count and max capacity in Json returned.

- Removed css !important and use class selector.

### CODE REVIEW

**Review by zhanshi-wang — APPROVED** [review]
Great, good tooltip exactly as  expected

**Comment by jain-nikunj** [comment]
LGTM - Can we fix the CodeClimate issues before merging? Looks like small edits to me.

**Review by aandreassa — APPROVED** [review]
Tooltip and map looks good to me. Good job

**Review by sunsun1001 — APPROVED** [review]
Good job. Thanks for fixing the code smells.

**Comment by kathrynwu** [comment]
Good job. Thanks for fixing the code smells and map looks good to me.

**Pull request merged**
